name: Deploy to Cloud Run

on:
push:
branches:
- dev
- qa
- prod

permissions:
contents: read
id-token: write

jobs:
deploy:
runs-on: ubuntu-latest

```
steps:
  - name: Set Environment Variables
    run: |
      if [ "${GITHUB_REF_NAME}" = "dev" ]; then
        echo "PROJECT_ID=dev-project-500104" >> $GITHUB_ENV
        echo "SERVICE_NAME=demo-app-dev" >> $GITHUB_ENV
      elif [ "${GITHUB_REF_NAME}" = "qa" ]; then
        echo "PROJECT_ID=qa-project-500104" >> $GITHUB_ENV
        echo "SERVICE_NAME=demo-app-qa" >> $GITHUB_ENV
      elif [ "${GITHUB_REF_NAME}" = "prod" ]; then
        echo "PROJECT_ID=prod-project-500104" >> $GITHUB_ENV
        echo "SERVICE_NAME=demo-app-prod" >> $GITHUB_ENV
      fi

  - name: Checkout
    uses: actions/checkout@v4

  - name: Authenticate to GCP
    uses: google-github-actions/auth@v2
    with:
      workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
      service_account: ${{ secrets.SERVICE_ACCOUNT }}

  - name: Setup GCloud
    uses: google-github-actions/setup-gcloud@v2

  - name: Configure Docker
    run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

  - name: Build Image
    run: docker build -t us-central1-docker.pkg.dev/$PROJECT_ID/app-repo/demo-app:${{ github.sha }} ./app

  - name: Push Image
    run: docker push us-central1-docker.pkg.dev/$PROJECT_ID/app-repo/demo-app:${{ github.sha }}

  - name: Deploy Cloud Run
    run: |
      gcloud run deploy $SERVICE_NAME \
        --image us-central1-docker.pkg.dev/$PROJECT_ID/app-repo/demo-app:${{ github.sha }} \
        --region us-central1 \
        --platform managed \
        --allow-unauthenticated
```
